# Generated by Django 2.1 on 2018-09-26 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourer', '0007_remove_tourer_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_status', models.CharField(max_length=5000)),
                ('end_status', models.CharField(max_length=5000)),
                ('img_status', models.FileField(default='/default/user-avatar-default-165.png', upload_to='vehicle/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnet', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 19, 55, 57, 22456))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
            ],
        ),
        migrations.CreateModel(
            name='Type_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vehicle', models.CharField(max_length=250)),
                ('garage', models.CharField(max_length=250)),
                ('img_vehicle', models.FileField(default='/default/user-avatar-default-165.png', upload_to='vehicle/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.City')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Type_vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_route', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('img_route', models.FileField(default='/default/user-avatar-default-165.png', upload_to='vehicle/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 19, 55, 57, 22456))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle_details')),
            ],
        ),
        migrations.AddField(
            model_name='comment_vehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle_details'),
        ),
        migrations.AddField(
            model_name='car_details',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle_details'),
        ),
    ]
