# Generated by Django 2.1 on 2018-09-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment_vehicle',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 20, 9, 4, 90652)),
        ),
        migrations.AlterField(
            model_name='vehicle_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 20, 9, 4, 91652)),
        ),
    ]
