# Generated by Django 2.1 on 2018-09-27 12:34

import book.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0003_auto_20180927_1934'),
        ('tourer', '0007_remove_tourer_time_create'),
        ('restaurants', '0004_auto_20180927_1934'),
        ('house', '0011_auto_20180927_1934'),
        ('places', '0005_auto_20180927_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_album', models.FileField(default='/default/user-avatar-default-165.png', upload_to='album/')),
                ('date_up', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 354572))),
            ],
        ),
        migrations.CreateModel(
            name='Book_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=250)),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 350573))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 350573))),
                ('tourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Tour_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book_Tour')),
            ],
        ),
        migrations.CreateModel(
            name='House_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 352572))),
                ('date_to', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 352572))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book_Tour')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='Place_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 351573))),
                ('date_to', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 351573))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book_Tour')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 351573))),
                ('date_to', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 351573))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book_Tour')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 352572))),
                ('date_to', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 352572))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book_Tour')),
                ('vehicle_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle_details')),
            ],
        ),
        migrations.AddField(
            model_name='book_tour_details',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.House_tour'),
        ),
        migrations.AddField(
            model_name='book_tour_details',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Place_tour'),
        ),
        migrations.AddField(
            model_name='book_tour_details',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Restaurant_tour'),
        ),
        migrations.AddField(
            model_name='book_tour_details',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Vehicle_tour'),
        ),
        migrations.AddField(
            model_name='album_tour',
            name='book',
            field=models.ForeignKey(on_delete=book.models.Book_Tour, to='book.Book_Tour'),
        ),
        migrations.AddField(
            model_name='album_tour',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Place_tour'),
        ),
    ]
